name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 20
      - name: Set output variable
        run: echo "OUTPUT_VAR=value" >> $GITHUB_ENV
        env:
          OUTPUT_VAR: value    
      - name: Checkout
        uses: actions/checkout@v1
      - run: npm install
      - run: npm run build 
      - run: npm test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS S3
        run: aws s3 sync $SOURCE_DIR s3://zinebreactappbucket
        env:
          SOURCE_DIR: 'build'      